{
	"version": 1639456866,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imageobject-sheet0.png",
		"images/imageobject-sheet1.png",
		"images/gameoverbackground-sheet0.png",
		"images/tryagainbackground-sheet0.png",
		"images/menubackground.png",
		"images/close-sheet0.png",
		"images/tiledbackground.png",
		"images/how2play-sheet0.png",
		"images/start-sheet0.png",
		"images/tiledbackground2.png",
		"media/correct.m4a",
		"media/correct.ogg",
		"media/wrong.m4a",
		"media/wrong.ogg",
		"media/well-done.m4a",
		"media/well-done.ogg",
		"media/wrong3.m4a",
		"media/wrong3.ogg",
		"media/correct3.m4a",
		"media/correct3.ogg",
		"media/wrong2.m4a",
		"media/wrong5.ogg",
		"media/wrong4.m4a",
		"media/wrong4.ogg",
		"media/android2.m4a",
		"media/android2.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/gameover1.m4a",
		"media/gameover1.ogg",
		"media/jetloop1.m4a",
		"media/jetloop1.ogg",
		"media/lazer fire 1.m4a",
		"media/lazer fire 1.ogg",
		"media/lazer ricochet.m4a",
		"media/lazer ricochet.ogg",
		"media/newachievement1.m4a",
		"media/newachievement1.ogg",
		"media/oooscary1.m4a",
		"media/oooscary1.ogg",
		"media/retrolaser1.m4a",
		"media/retrolaser1.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"media/sfx5.m4a",
		"media/sfx5.ogg",
		"media/squaremotif1.m4a",
		"media/squaremotif1.ogg",
		"media/sword swing.m4a",
		"media/sword swing.ogg",
		"media/tronblast1.m4a",
		"media/tronblast1.ogg",
		"media/ui1.m4a",
		"media/ui1.ogg",
		"media/upgrade1.m4a",
		"media/upgrade1.ogg",
		"media/cancel - 1.m4a",
		"media/cancel - 1.ogg",
		"media/menu click 2.m4a",
		"media/menu click 2.ogg",
		"media/squaremotif2.m4a",
		"media/squaremotif2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}